# Generated by Django 5.0.6 on 2024-09-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('logo_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
