# Generated by Django 5.0.6 on 2025-01-12 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_transcription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='consultation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='consultations.consultation'),
        ),
        migrations.AlterField(
            model_name='soapnotes',
            name='consultation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soap_note', to='consultations.consultation'),
        ),
    ]
