# Generated by Django 5.0.6 on 2025-01-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_alter_prescription_consultation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soapnotes',
            name='subject',
        ),
    ]
