# Generated by Django 5.0.6 on 2025-01-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_remove_soapnotes_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='instruction',
            new_name='additional_info',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicine_name',
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicines',
            field=models.JSONField(default=list),
        ),
    ]
