# Generated by Django 5.0.6 on 2025-01-12 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_rename_instruction_prescription_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='consultation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcription', to='consultations.consultation'),
        ),
    ]
