# Generated by Django 5.0.6 on 2024-11-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='pmdc_file',
            field=models.FileField(blank=True, null=True, upload_to='pmdc_files/'),
        ),
    ]
