# Generated by Django 5.0.6 on 2024-09-29 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_allergy'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.allergy')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.patientprofile')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.doctorprofile')),
            ],
            options={
                'unique_together': {('allergy', 'patient')},
            },
        ),
    ]
